version: 1.0.{build}
before_build:
  - nuget restore
build:
  verbosity: minimal
after_build:
- cmd: >-
    7z a asmspy.zip .\AsmSpy.CommandLine\bin\Debug\AsmSpy.exe

    if defined APPVEYOR_REPO_TAG_NAME choco pack .\AsmSpy.CommandLine\AsmSpy.nuspec --version %APPVEYOR_REPO_TAG_NAME%

    if defined APPVEYOR_REPO_TAG_NAME appveyor PushArtifact asmspy.%APPVEYOR_REPO_TAG_NAME%.nupkg -DeploymentName ReleaseNuget
artifacts:
- path: asmspy.zip
  name: Zip Package