version: 1.3.{build}
before_build:
  - nuget restore
# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.3.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
build:
  verbosity: minimal
after_build:
- cmd: >-
    7z a asmspy.zip .\AsmSpy.CommandLine\bin\Debug\AsmSpy.exe

    choco pack .\AsmSpy.CommandLine\AsmSpy.nuspec --version %APPVEYOR_BUILD_VERSION%

    appveyor PushArtifact asmspy.%APPVEYOR_BUILD_VERSION%.nupkg -DeploymentName ReleaseChoco
    
    nuget pack .\AsmSpy\AsmSpy.nuspec -version %APPVEYOR_BUILD_VERSION%

    appveyor PushArtifact asmspy.%APPVEYOR_BUILD_VERSION%.nupkg -DeploymentName ReleaseChoco
artifacts:
- path: asmspy.{version}.zip
  name: Zip Package
- path: '\AsmSpy.CommandLine\asmspy.{version}.nupkg'
  name: Chocolatey Package
- path: '\AsmSpy\asmspy.{version}.nupkg'
  name: NuGet Package